name: Unit Tests

on: [pull_request, workflow_dispatch]

jobs:
  test:

    runs-on: windows-latest

    steps:
    - name: Check out repo contents
      uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
        architecture: "x86"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r RP1210/requirements.txt
    - name: Test with pytest
      run: |
        tree /F
        python -m pytest -v
